version: '3.7'

services:
  php-fpm:
    build:
      context: ./
      dockerfile: Dockerfile.php-fpm
      target: release

  nginx:
    build:
      context: ./
      dockerfile: Dockerfile.nginx

  dynamodb:
    image: amazon/dynamodb-local:latest
