FROM php:7.4.2-fpm-buster AS base

RUN docker-php-ext-install pdo_mysql

COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer

WORKDIR /app

FROM base AS release
COPY ./ /app
RUN chown -R www-data:www-data /app
RUN ln -s php.ini-production /usr/local/etc/php/php.ini

FROM base AS develop
RUN ln -s php.ini-development /usr/local/etc/php/php.ini
RUN usermod -s /bin/bash -u 1000 www-data
RUN groupmod -g 1000 www-data
RUN chown www-data:www-data /var/www
