version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.4-cli-node

    steps:
      - checkout

      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.lock" }}
          paths:
            - ./vendor

      - run: sudo npm i -g serverless
      - run: sls deploy
